"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import tempfile
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(env_path):
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


load_env_file(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default

    return value.lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    value = os.getenv(name)
    if not value:
        return list(default or [])

    return [item.strip() for item in value.split(",") if item.strip()]


IS_VERCEL = bool(os.getenv("VERCEL"))


def clean_env_value(value):
    if value is None:
        return None

    value = value.strip().strip('"').strip("'")
    return value or None


def build_sqlite_database(name):
    return {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": name,
        }
    }


def build_postgres_database(database_url):
    database_url = clean_env_value(database_url)
    parsed = urlparse(database_url)
    scheme = parsed.scheme.lower()

    if "postgres" not in scheme:
        raise ValueError(f"Unsupported DATABASE_URL scheme: {parsed.scheme}")

    database_name = unquote(parsed.path.lstrip("/"))
    if not database_name:
        raise ValueError("DATABASE_URL must include a database name")

    try:
        port = str(parsed.port or "")
    except ValueError as exc:
        raise ValueError(f"Invalid DATABASE_URL port: {parsed.netloc}") from exc

    query = parse_qs(parsed.query)
    sslmode = query.get(
        "sslmode",
        [os.getenv("DB_SSLMODE", "require" if IS_VERCEL else "prefer")],
    )[0]

    options = {}
    if sslmode:
        options["sslmode"] = sslmode

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": database_name,
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": port,
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "0" if IS_VERCEL else "60")),
        "DISABLE_SERVER_SIDE_CURSORS": env_bool("DB_DISABLE_SERVER_SIDE_CURSORS", default=True),
        "OPTIONS": options,
    }


def get_database_url():
    for env_name in ("DATABASE_URL", "POSTGRES_URL_NON_POOLING", "POSTGRES_URL"):
        value = clean_env_value(os.getenv(env_name))
        if value:
            return value

    return None


def build_database_settings(database_url=None):
    database_url = clean_env_value(database_url) or get_database_url()

    if database_url:
        try:
            return {"default": build_postgres_database(database_url)}
        except ValueError:
            if not IS_VERCEL:
                raise

    if IS_VERCEL:
        return build_sqlite_database(Path(tempfile.gettempdir()) / "hangarin" / "db.sqlite3")

    return build_sqlite_database(BASE_DIR / "db.sqlite3")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    os.getenv(
        "SECRET_KEY",
        "django-insecure-e9l00swz#_r&9i6y1r-!f1$gk+aw5jyy$&#o$796&p)5v1(po7",
    ),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # env_bool("DJANGO_DEBUG", default=not IS_VERCEL)
PWA_ENABLED = env_bool("PWA_ENABLED", default=not DEBUG)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", [
    '127.0.0.1',
    'localhost',
    'testserver',
    'richo.pythonanywhere.com',
    'richo1.pythonanywhere.com',
    '192.168.100.14',
    'lithological-midsize-polyphonically.ngrok-free.app',
    '*' # Allows access from any ngrok URL automatically
])

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

if os.getenv("VERCEL_URL"):
    vercel_origin = f"https://{os.getenv('VERCEL_URL')}"
    if vercel_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(vercel_origin)

# Necessary for PythonAnywhere and other proxies to handle HTTPS correctly
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "tasks",
    "pwa",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "tasks.middleware.ServerlessDatabaseBootstrapMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "tasks.context_processors.app_flags",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
SOCIALACCOUNT_ADAPTER = "tasks.adapters.HangarinSocialAccountAdapter"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = get_database_url()
DATABASES = build_database_settings(DATABASE_URL)
EPHEMERAL_SQLITE_DATABASE = (
    IS_VERCEL and DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3"
)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

if EPHEMERAL_SQLITE_DATABASE:
    SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/login/"
ACCOUNT_LOGIN_REDIRECT_URL = LOGIN_REDIRECT_URL
ACCOUNT_LOGOUT_REDIRECT_URL = LOGOUT_REDIRECT_URL
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "").strip()
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "").strip()
GOOGLE_OAUTH_ENABLED = bool(GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET)
GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID", "").strip()
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET", "").strip()
GITHUB_OAUTH_ENABLED = bool(GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET)
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "APPS": (
            [
                {
                    "client_id": GOOGLE_CLIENT_ID,
                    "secret": GOOGLE_CLIENT_SECRET,
                    "key": "",
                    "settings": {
                        "scope": ["profile", "email"],
                        "auth_params": {"access_type": "online"},
                    },
                }
            ]
            if GOOGLE_OAUTH_ENABLED
            else []
        ),
    },
    "github": {
        "SCOPE": ["read:user", "user:email"],
        "APPS": (
            [
                {
                    "client_id": GITHUB_CLIENT_ID,
                    "secret": GITHUB_CLIENT_SECRET,
                    "key": "",
                    "settings": {
                        "scope": ["read:user", "user:email"],
                    },
                }
            ]
            if GITHUB_OAUTH_ENABLED
            else []
        ),
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- Progressive Web App Settings ---
PWA_APP_NAME = 'Hangarin'
PWA_APP_DESCRIPTION = "A Progressive Web App version of Hangarin"
PWA_APP_DEBUG_MODE = DEBUG
PWA_APP_THEME_COLOR = '#0A0A0A'
PWA_APP_BACKGROUND_COLOR = '#FFFFFF'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/tasks/icon-192.png',
        'sizes': '192x192'
    },
    {
        'src': '/static/tasks/icon-512.png',
        'sizes': '512x512'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/tasks/icon-192.png',
        'sizes': '192x192'
    },
    {
        'src': '/static/tasks/icon-512.png',
        'sizes': '512x512'
    }
]
PWA_APP_DIR = 'ltr'
PWA_SERVICE_WORKER_PATH = (
    os.path.join(BASE_DIR, 'static', 'js', 'serviceworker.js')
    if PWA_ENABLED
    else os.path.join(BASE_DIR, 'config', 'serviceworker_dev.js')
)
